# SPDX-FileCopyrightText: 2020 SAP SE
# SPDX-FileCopyrightText: 2021 SAP SE
# SPDX-FileCopyrightText: 2022 SAP SE
# SPDX-FileCopyrightText: 2023 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

GO ?= go

REUSE_ARGS = --skip-unrecognised --copyright='SAP SE' --license='Apache-2.0'

generate:
ifeq (x$(TARGET),x)
	grep -r '^// Code generated by ".*"\; DO NOT EDIT.$\' ./ | awk -F: '{ print $$1 }' | xargs --no-run-if-empty rm
	$(GO) generate ./...
	reuse addheader $(REUSE_ARGS) $(shell find . -type f -not -path '*/.git/*')
else
	grep '^// Code generated by ".*"\; DO NOT EDIT.$\' ./$(TARGET)/* | awk -F: '{ print $$1 }' | xargs --no-run-if-empty rm
	$(GO) generate ./$(TARGET)
	reuse addheader $(REUSE_ARGS) $(shell find ./$(TARGET) -type f -not -path '*/.git/*')
endif

lint:
	golangci-lint run ./...

test:
	$(GO) test -race -cover ./...

.PHONY: report
report:
	$(GO) clean -testcache
	$(GO) test -race -cover -coverprofile=/tmp/cov.out ./...
	$(GO) tool cover -html=/tmp/cov.out -o ./report.html
	rm /tmp/cov.out
