// SPDX-FileCopyrightText: 2021 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=CursorIStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_CUR_ISTAT_UNUSED-0]
	_ = x[TDS_CUR_ISTAT_DECLARED-1]
	_ = x[TDS_CUR_ISTAT_OPEN-2]
	_ = x[TDS_CUR_ISTAT_CLOSED-4]
	_ = x[TDS_CUR_ISTAT_RDONLY-8]
	_ = x[TDS_CUR_ISTAT_UPDATABLE-16]
	_ = x[TDS_CUR_ISTAT_ROWCNT-32]
	_ = x[TDS_CUR_ISTAT_DEALLOC-64]
	_ = x[TDS_CUR_ISTAT_SCROLLABLE-128]
	_ = x[TDS_CUR_ISTAT_IMPLICIT-256]
	_ = x[TDS_CUR_ISTAT_SENSITIVE-512]
	_ = x[TDS_CUR_ISTAT_INSENSITIVE-1024]
	_ = x[TDS_CUR_ISTAT_SEMISENSITIVE-2048]
	_ = x[TDS_CUR_ISTAT_KEYSETDRIVEN-4096]
	_ = x[TDS_CUR_ISTAT_RELLOCKSONCLOSE-8192]
}

const _CursorIStatus_name = "TDS_CUR_ISTAT_UNUSEDTDS_CUR_ISTAT_DECLAREDTDS_CUR_ISTAT_OPENTDS_CUR_ISTAT_CLOSEDTDS_CUR_ISTAT_RDONLYTDS_CUR_ISTAT_UPDATABLETDS_CUR_ISTAT_ROWCNTTDS_CUR_ISTAT_DEALLOCTDS_CUR_ISTAT_SCROLLABLETDS_CUR_ISTAT_IMPLICITTDS_CUR_ISTAT_SENSITIVETDS_CUR_ISTAT_INSENSITIVETDS_CUR_ISTAT_SEMISENSITIVETDS_CUR_ISTAT_KEYSETDRIVENTDS_CUR_ISTAT_RELLOCKSONCLOSE"

var _CursorIStatus_map = map[CursorIStatus]string{
	0:    _CursorIStatus_name[0:20],
	1:    _CursorIStatus_name[20:42],
	2:    _CursorIStatus_name[42:60],
	4:    _CursorIStatus_name[60:80],
	8:    _CursorIStatus_name[80:100],
	16:   _CursorIStatus_name[100:123],
	32:   _CursorIStatus_name[123:143],
	64:   _CursorIStatus_name[143:164],
	128:  _CursorIStatus_name[164:188],
	256:  _CursorIStatus_name[188:210],
	512:  _CursorIStatus_name[210:233],
	1024: _CursorIStatus_name[233:258],
	2048: _CursorIStatus_name[258:285],
	4096: _CursorIStatus_name[285:311],
	8192: _CursorIStatus_name[311:340],
}

func (i CursorIStatus) String() string {
	if str, ok := _CursorIStatus_map[i]; ok {
		return str
	}
	return "CursorIStatus(" + strconv.FormatInt(int64(i), 10) + ")"
}
