// SPDX-FileCopyrightText: 2021 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=CursorDStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_CUR_DSTAT_UNUSED-0]
	_ = x[TDS_CUR_DSTAT_HASARGS-1]
}

const _CursorDStatus_name = "TDS_CUR_DSTAT_UNUSEDTDS_CUR_DSTAT_HASARGS"

var _CursorDStatus_index = [...]uint8{0, 20, 41}

func (i CursorDStatus) String() string {
	if i >= CursorDStatus(len(_CursorDStatus_index)-1) {
		return "CursorDStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CursorDStatus_name[_CursorDStatus_index[i]:_CursorDStatus_index[i+1]]
}
