// SPDX-FileCopyrightText: 2020-2025 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=CursorDeleteStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_CUR_DELSTAT_UNUSED-0]
}

const _CursorDeleteStatus_name = "TDS_CUR_DELSTAT_UNUSED"

var _CursorDeleteStatus_index = [...]uint8{0, 22}

func (i CursorDeleteStatus) String() string {
	if i >= CursorDeleteStatus(len(_CursorDeleteStatus_index)-1) {
		return "CursorDeleteStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CursorDeleteStatus_name[_CursorDeleteStatus_index[i]:_CursorDeleteStatus_index[i+1]]
}
