// SPDX-FileCopyrightText: 2022 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gen_type NullDecimal github.com/SAP/go-dblib/asetypes.NullDecimal -columndef decimal(38,19) null -convert convertNullDecimal -compare compareNullDecimal"; DO NOT EDIT.

package integration

import (
	"database/sql"

	"github.com/SAP/go-dblib/asetypes"

	"testing"
)

// DoTestNullDecimal tests the handling of the NullDecimal.
func DoTestNullDecimal(t *testing.T) {
	TestForEachDB("TestNullDecimal", t, testNullDecimal)
	//
}

func testNullDecimal(t *testing.T, db *sql.DB, tableName string) {
	// insert is the amount of insertions (see fn SetupTableInsert)
	insert := 2

	pass := make([]interface{}, len(samplesNullDecimal))
	mySamples := make([]asetypes.NullDecimal, len(samplesNullDecimal)*insert)

	for i, sample := range samplesNullDecimal {

		// Convert sample with passed function before proceeding
		mySample, err := convertNullDecimal(sample)
		if err != nil {
			t.Errorf("Failed to convert sample %v: %v", sample, err)
			return
		}

		pass[i] = mySample

		// Add passed sample for the later validation (for every
		// insert)
		for j := 0; j < insert; j++ {
			mySamples[i+(len(samplesNullDecimal)*j)] = mySample
		}
	}

	rows, teardownFn, err := SetupTableInsert(db, tableName, "decimal(38,19) null", pass...)
	if err != nil {
		t.Errorf("Error preparing table: %v", err)
		return
	}
	defer rows.Close()
	defer teardownFn()

	i := 0
	var recv asetypes.NullDecimal
	for rows.Next() {
		if err := rows.Scan(&recv); err != nil {
			t.Errorf("Scan failed on %dth scan: %v", i, err)
			continue
		}

		if compareNullDecimal(recv, mySamples[i]) {

			t.Errorf("Received value does not match passed parameter")
			t.Errorf("Expected: %v", mySamples[i])
			t.Errorf("Received: %v", recv)
		}

		i++
	}

	if err := rows.Err(); err != nil {
		t.Errorf("Error preparing rows: %v", err)
	}

	if i != len(pass)*insert {
		t.Errorf("Only read %d values from database, expected to read %d", i, len(pass)*insert)
	}
}
