// SPDX-FileCopyrightText: 2020-2025 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gen_type VarBinary []byte -columndef varbinary(13) -compare compareVarBinary"; DO NOT EDIT.

package integration

import (
	"database/sql"

	"testing"
)

// DoTestVarBinary tests the handling of the VarBinary.
func DoTestVarBinary(t *testing.T) {
	TestForEachDB("TestVarBinary", t, testVarBinary)
	//
}

func testVarBinary(t *testing.T, db *sql.DB, tableName string) {
	// insert is the amount of insertions (see fn SetupTableInsert)
	insert := 2

	pass := make([]interface{}, len(samplesVarBinary))
	mySamples := make([][]byte, len(samplesVarBinary)*insert)

	for i, sample := range samplesVarBinary {

		mySample := sample

		pass[i] = mySample

		// Add passed sample for the later validation (for every
		// insert)
		for j := 0; j < insert; j++ {
			mySamples[i+(len(samplesVarBinary)*j)] = mySample
		}
	}

	rows, teardownFn, err := SetupTableInsert(db, tableName, "varbinary(13)", pass...)
	if err != nil {
		t.Errorf("Error preparing table: %v", err)
		return
	}
	defer rows.Close()
	defer teardownFn()

	i := 0
	var recv []byte
	for rows.Next() {
		if err := rows.Scan(&recv); err != nil {
			t.Errorf("Scan failed on %dth scan: %v", i, err)
			continue
		}

		if compareVarBinary(recv, mySamples[i]) {

			t.Errorf("Received value does not match passed parameter")
			t.Errorf("Expected: %v", mySamples[i])
			t.Errorf("Received: %v", recv)
		}

		i++
	}

	if err := rows.Err(); err != nil {
		t.Errorf("Error preparing rows: %v", err)
	}

	if i != len(pass)*insert {
		t.Errorf("Only read %d values from database, expected to read %d", i, len(pass)*insert)
	}
}
