// SPDX-FileCopyrightText: 2022 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "gen_type Decimal10 github.com/SAP/go-dblib/*asetypes.Decimal -columndef decimal(1,0) -convert convertDecimal10 -compare compareDecimal"; DO NOT EDIT.

package integration

import (
	"database/sql"

	"github.com/SAP/go-dblib/asetypes"

	"testing"
)

// DoTestDecimal10 tests the handling of the Decimal10.
func DoTestDecimal10(t *testing.T) {
	TestForEachDB("TestDecimal10", t, testDecimal10)
	//
}

func testDecimal10(t *testing.T, db *sql.DB, tableName string) {
	// insert is the amount of insertions (see fn SetupTableInsert)
	insert := 2

	pass := make([]interface{}, len(samplesDecimal10))
	mySamples := make([]*asetypes.Decimal, len(samplesDecimal10)*insert)

	for i, sample := range samplesDecimal10 {

		// Convert sample with passed function before proceeding
		mySample, err := convertDecimal10(sample)
		if err != nil {
			t.Errorf("Failed to convert sample %v: %v", sample, err)
			return
		}

		pass[i] = mySample

		// Add passed sample for the later validation (for every
		// insert)
		for j := 0; j < insert; j++ {
			mySamples[i+(len(samplesDecimal10)*j)] = mySample
		}
	}

	rows, teardownFn, err := SetupTableInsert(db, tableName, "decimal(1,0)", pass...)
	if err != nil {
		t.Errorf("Error preparing table: %v", err)
		return
	}
	defer rows.Close()
	defer teardownFn()

	i := 0
	var recv *asetypes.Decimal
	for rows.Next() {
		if err := rows.Scan(&recv); err != nil {
			t.Errorf("Scan failed on %dth scan: %v", i, err)
			continue
		}

		if compareDecimal(recv, mySamples[i]) {

			t.Errorf("Received value does not match passed parameter")
			t.Errorf("Expected: %v", mySamples[i])
			t.Errorf("Received: %v", recv)
		}

		i++
	}

	if err := rows.Err(); err != nil {
		t.Errorf("Error preparing rows: %v", err)
	}

	if i != len(pass)*insert {
		t.Errorf("Only read %d values from database, expected to read %d", i, len(pass)*insert)
	}
}
